# printable_card.py
from PIL import Image, ImageDraw, ImageFont

def generate_printable_card(name, school, goal, captured_img, ai_img, logo_file=None):
    """
    Creates a printable A4 portrait card (PNG) with student info + photos.
    """
    WIDTH, HEIGHT = 2480, 3508  # A4 @ 300 DPI
    card = Image.new("RGB", (WIDTH, HEIGHT), "white")
    draw = ImageDraw.Draw(card)

    # Load fonts (use default PIL fonts if custom fonts unavailable)
    try:
        title_font = ImageFont.truetype("Arial.ttf", 90)
        subtitle_font = ImageFont.truetype("Arial.ttf", 60)
        small_font = ImageFont.truetype("Arial.ttf", 45)
    except:
        title_font = ImageFont.load_default()
        subtitle_font = ImageFont.load_default()
        small_font = ImageFont.load_default()

    # Header text
    draw.text((WIDTH/2, 120), f"{name}'s Future Goal", anchor="mm", font=title_font, fill="black")
    draw.text((WIDTH/2, 220), f"Future: {goal}", anchor="mm", font=subtitle_font, fill="gray")

    if school:
        draw.text((WIDTH/2, 320), f"School: {school}", anchor="mm", font=small_font, fill="gray")

    # Logo
    if logo_file:
        logo = Image.open(logo_file).convert("RGBA")
        logo.thumbnail((300, 300))
        card.paste(logo, (80, 80), logo)

    # Resize photos
    captured_resized = captured_img.resize((1000, 1300))
    ai_resized = ai_img.resize((1000, 1300))

    # Paste images
    card.paste(captured_resized, (200, 600))
    card.paste(ai_resized, (1280, 600))

    # Footer
    draw.text((WIDTH/2, HEIGHT - 200),
              "Generated by Future Goal AI",
              anchor="mm", font=small_font, fill="gray")

    return card
